export const phrases = {
  en: {
    translation: {
      roll: "Roll Dice",
      rolling: "Rolling...",
      repeat: "Repeat",
      noRepeat: "No Repeat",
      shareApp: "Share",
      shareAppMessage: "App to heat up the relationship 🔥",
      rateApp: "Rate App",
      language: "Language",
      comingSoon: "Coming Soon",
      tasks: [
        "Kiss or pinch",
        "Hug or rub",
        "Caress or tickle",
        "Touch or squeeze",
        "Lick or smear",
        "Suck or bite",
      ],
      locations: [
        "Neck",
        "Chest",
        "Legs",
        "Right there... 🎯",
        "Butt",
        "Mouth",
      ],
    },
  },
  pt: {
    translation: {
      roll: "Rolar Dados",
      rolling: "Rolando...",
      repeat: "Repetir",
      noRepeat: "Não Repetir",
      shareApp: "Compartilhar",
      shareAppMessage: "App para esquentar a relação 🔥",
      rateApp: "Avaliar",
      language: "Idioma",
      comingSoon: "Em Breve",
      tasks: [
        "Beijar ou beliscar",
        "Abraçar ou se esfregar",
        "Acariciar ou fazer cócegas",
        "Tocar ou apertar",
        "Lamber ou lambuzar",
        "Chupar ou morder",
      ],
      locations: [
        "Pescoço",
        "Peito",
        "Pernas",
        "Lá mesmo... 🎯",
        "Bunda",
        "Boca",
      ],
    },
  },
  es: {
    translation: {
      roll: "Lanzar Dados",
      rolling: "Lanzando...",
      repeat: "Repetir",
      noRepeat: "No Repetir",
      shareApp: "Compartir",
      shareAppMessage: "App para calentar la relación 🔥",
      rateApp: "Calificar",
      language: "Idioma",
      comingSoon: "Próximamente",
      tasks: [
        "Besos o pellizcos",
        "Abrazos o frotar",
        "Caricias o cosquillas",
        "Tocar o apretar",
        "Lamer o untar",
        "Chupar o morder",
      ],
      locations: [
        "Cuello",
        "Pecho",
        "Piernas",
        "Ahí mismo... 🎯",
        "Cola",
        "Boca",
      ],
    },
  },
  zh: {
    translation: {
      roll: "掷骰子",
      rolling: "滚动中...",
      repeat: "重复",
      noRepeat: "不重复",
      shareApp: "分享",
      shareAppMessage: "让关系升温的应用 🔥",
      rateApp: "评分",
      language: "语言",
      comingSoon: "即将推出",
      tasks: [
        "亲吻或捏",
        "拥抱或摩擦",
        "抚摸或挠痒",
        "触摸或挤压",
        "舔或涂抹",
        "吮吸或咬",
      ],
      locations: ["脖子", "胸部", "腿", "就在那里... 🎯", "臀部", "嘴"],
    },
  },
  de: {
    translation: {
      roll: "Würfeln",
      rolling: "Würfeln...",
      repeat: "Wiederholen",
      noRepeat: "Nicht Wiederholen",
      shareApp: "Teilen",
      shareAppMessage: "App zum Aufheizen der Beziehung 🔥",
      rateApp: "Bewerten",
      language: "Sprache",
      comingSoon: "Demnächst",
      tasks: [
        "Küssen oder kneifen",
        "Umarmen oder reiben",
        "Streicheln oder kitzeln",
        "Berühren oder drücken",
        "Lecken oder schmieren",
        "Saugen oder beißen",
      ],
      locations: ["Hals", "Brust", "Beine", "Genau dort... 🎯", "Po", "Mund"],
    },
  },
  hi: {
    translation: {
      roll: "पासा फेंको",
      rolling: "फेंक रहा है...",
      repeat: "दोहराएं",
      noRepeat: "दोहराएं नहीं",
      shareApp: "शेयर",
      shareAppMessage: "रिश्ते को गर्म करने वाला ऐप 🔥",
      rateApp: "रेट करें",
      language: "भाषा",
      comingSoon: "जल्द आ रहा है",
      tasks: [
        "चुंबन या चुटकी",
        "गले लगाना या रगड़ना",
        "सहलाना या गुदगुदी",
        "छूना या दबाना",
        "चाटना या लगाना",
        "चूसना या काटना",
      ],
      locations: ["गर्दन", "छाती", "पैर", "वहीं... 🎯", "गधा", "मुंह"],
    },
  },
};
