export const phrases = {
  en: {
    translation: {
      roll: "Roll Dice",
      rolling: "Rolling...",
      repeat: "Repeat",
      noRepeat: "No Repeat",
      shareApp: "Share",
      shareAppMessage: "App to heat up the relationship 🔥",
      rateApp: "Rate App",
      language: "English",
      comingSoon: "Coming Soon",
      diceGameDescription:
        "Roll the dice and discover exciting challenges to spice up your relationship",
      newFeatureDescription:
        "New features coming soon to make your moments even more special",
      tasks: [
        "Kiss or pinch",
        "Hug or rub",
        "Caress or tickle",
        "Touch or squeeze",
        "Lick or smear",
        "Suck or bite",
      ],
      locations: [
        "Neck",
        "Chest",
        "Legs",
        "Right there... 🎯",
        "Butt",
        "Mouth",
      ],
    },
  },
  pt: {
    translation: {
      roll: "Rolar Dados",
      rolling: "Rolando...",
      repeat: "Repetir",
      noRepeat: "Não Repetir",
      shareApp: "Compartilhar",
      shareAppMessage: "App para esquentar a relação 🔥",
      rateApp: "Avaliar",
      language: "Português",
      comingSoon: "Em Breve",
      diceGameDescription:
        "Role os dados e descubra desafios excitantes para esquentar sua relação",
      newFeatureDescription:
        "Novas funcionalidades em breve para tornar seus momentos ainda mais especiais",
      tasks: [
        "Beijar ou beliscar",
        "Abraçar ou se esfregar",
        "Acariciar ou fazer cócegas",
        "Tocar ou apertar",
        "Lamber ou lambuzar",
        "Chupar ou morder",
      ],
      locations: [
        "Pescoço",
        "Peito",
        "Pernas",
        "Lá mesmo... 🎯",
        "Bunda",
        "Boca",
      ],
    },
  },
  es: {
    translation: {
      roll: "Lanzar Dados",
      rolling: "Lanzando...",
      repeat: "Repetir",
      noRepeat: "No Repetir",
      shareApp: "Compartir",
      shareAppMessage: "App para calentar la relación 🔥",
      rateApp: "Calificar",
      language: "Español",
      comingSoon: "Próximamente",
      diceGameDescription:
        "Lanza los dados y descubre emocionantes desafíos para calentar tu relación",
      newFeatureDescription:
        "Nuevas funciones próximamente para hacer tus momentos aún más especiales",
      tasks: [
        "Besos o pellizcos",
        "Abrazos o frotar",
        "Caricias o cosquillas",
        "Tocar o apretar",
        "Lamer o untar",
        "Chupar o morder",
      ],
      locations: [
        "Cuello",
        "Pecho",
        "Piernas",
        "Ahí mismo... 🎯",
        "Cola",
        "Boca",
      ],
    },
  },
  zh: {
    translation: {
      roll: "掷骰子",
      rolling: "滚动中...",
      repeat: "重复",
      noRepeat: "不重复",
      shareApp: "分享",
      shareAppMessage: "让关系升温的应用 🔥",
      rateApp: "评分",
      language: "中文",
      comingSoon: "即将推出",
      diceGameDescription: "掷骰子，发现令人兴奋的挑战，让您的关系升温",
      newFeatureDescription: "即将推出新功能，让您的时刻更加特别",
      tasks: [
        "亲吻或捏",
        "拥抱或摩擦",
        "抚摸或挠痒",
        "触摸或挤压",
        "舔或涂抹",
        "吮吸或咬",
      ],
      locations: ["脖子", "胸部", "腿", "就在那里... 🎯", "臀部", "嘴"],
    },
  },
  de: {
    translation: {
      roll: "Würfeln",
      rolling: "Würfeln...",
      repeat: "Wiederholen",
      noRepeat: "Nicht Wiederholen",
      shareApp: "Teilen",
      shareAppMessage: "App zum Aufheizen der Beziehung 🔥",
      rateApp: "Bewerten",
      language: "Deutsch",
      comingSoon: "Demnächst",
      diceGameDescription:
        "Würfeln Sie und entdecken Sie aufregende Herausforderungen, um Ihre Beziehung zu befeuern",
      newFeatureDescription:
        "Neue Funktionen kommen bald, um Ihre Momente noch spezieller zu machen",
      tasks: [
        "Küssen oder kneifen",
        "Umarmen oder reiben",
        "Streicheln oder kitzeln",
        "Berühren oder drücken",
        "Lecken oder schmieren",
        "Saugen oder beißen",
      ],
      locations: ["Hals", "Brust", "Beine", "Genau dort... 🎯", "Po", "Mund"],
    },
  },
  hi: {
    translation: {
      roll: "पासा फेंको",
      rolling: "फेंक रहा है...",
      repeat: "दोहराएं",
      noRepeat: "दोहराएं नहीं",
      shareApp: "शेयर",
      shareAppMessage: "रिश्ते को गर्म करने वाला ऐप 🔥",
      rateApp: "रेट करें",
      language: "हिन्दी",
      comingSoon: "जल्द आ रहा है",
      diceGameDescription:
        "पासा फेंकें और अपने रिश्ते को गर्म करने के लिए रोमांचक चुनौतियों की खोज करें",
      newFeatureDescription:
        "आपके पलों को और भी खास बनाने के लिए जल्द ही नई सुविधाएं आ रही हैं",
      tasks: [
        "चुंबन या चुटकी",
        "गले लगाना या रगड़ना",
        "सहलाना या गुदगुदी",
        "छूना या दबाना",
        "चाटना या लगाना",
        "चूसना या काटना",
      ],
      locations: ["गर्दन", "छाती", "पैर", "वहीं... 🎯", "गधा", "मुंह"],
    },
  },
};
