name: EAS Build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar EAS CLI
        run: npm install -g eas-cli

      - name: Login no Expo
        run: eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: Build para produção
        run: eas build --platform all --profile production --non-interactive
