import { StyleSheet } from "react-native";

export const DiceGameStyles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 40,
  },
  header: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "center",
    width: "100%",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 30,
    padding: 4,
  },
  toggleContainer: {
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 2,
    height: 44,
    width: "100%",
  },
  headerButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
    minWidth: 70,
    height: 60,
  },
  headerButtonContent: {
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    height: 44,
  },
  headerButtonFlag: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
    minWidth: 70,
    height: 60,
  },
  headerButtonText: {
    fontSize: 20,
  },
  headerButtonLabel: {
    color: "#ffffff",
    fontSize: 12,
    textAlign: "center",
    flexWrap: "wrap",
    maxWidth: "100%",
  },

  toggleLabel: {
    color: "#ffffff",
    fontSize: 12,
    textAlign: "center",
    flexWrap: "wrap",
    maxWidth: 68,
  },
  toggleSwitch: {
    width: 36,
    height: 20,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 10,
    padding: 2,
    justifyContent: "center",
  },
  toggleSwitchActive: {
    backgroundColor: "rgba(255, 0, 0, 0.3)",
  },
  toggleKnob: {
    width: 16,
    height: 16,
    backgroundColor: "#ffffff",
    borderRadius: 8,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 2,
  },
  toggleKnobActive: {
    backgroundColor: "#ff0000",
    transform: [{ translateX: 16 }],
  },
  diceContainer: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    gap: 48,
  },
  diceAlign: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 40,
  },
  dice: {
    width: 120,
    height: 120,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#ff0000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
    borderWidth: 2,
    borderColor: "#ff0000",
    backgroundColor: "rgba(255, 255, 255, 0.9)",
  },
  diceFace: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    padding: 8,
    borderRadius: 18,
  },
  diceText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#ff0000",
    textAlign: "center",
    lineHeight: 20,
    width: "100%",
  },
  buttonContainer: {
    alignItems: "center",
  },
  button: {
    borderRadius: 25,
    overflow: "hidden",
    shadowColor: "#ff0000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    borderWidth: 2,
    borderColor: "#ffffff",
    width: 200,
  },
  buttonGradient: {
    paddingHorizontal: 40,
    paddingVertical: 15,
  },
  buttonDisabled: {
    opacity: 0.7,
  },
  buttonText: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "bold",
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
    textAlign: "center",
  },
  shareButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  shareButtonText: {
    fontSize: 20,
  },
  actionButtonsContainer: {
    position: "absolute",
    right: 24,
    top: 260,
    transform: [{ translateY: -100 }],
    alignItems: "center",
    gap: 16,
  },
  actionButton: {
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    padding: 12,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
    alignItems: "center",
    width: 80,
  },
  actionButtonText: {
    fontSize: 24,
    marginBottom: 4,
  },
  actionButtonLabel: {
    color: "#ffffff",
    fontSize: 12,
    textAlign: "center",
  },
});
